name: Publish Source

env:
  CI: true

on:
  push:
    branches:
      - source
      - 'releases/**'
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        run: npm install -g yarn && yarn install --frozen-lockfile && yarn deploy
